apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ner-network-policy
  namespace: ner-app
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ner-app
    - podSelector:
        matchLabels:
          app: ner-frontend
    ports:
    - protocol: TCP
      port: 8000
  - from:
    - namespaceSelector:
        matchLabels:
          name: ner-app
    ports:
    - protocol: TCP
      port: 8501
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: ner-app
    ports:
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 8501
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
